# Generated by Django 4.1.2 on 2024-02-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='title',
            new_name='near_city',
        ),
        migrations.AddField(
            model_name='destinations',
            name='place',
            field=models.CharField(default='Pune', max_length=100),
            preserve_default=False,
        ),
    ]
